//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Microservices.Service"/> </summary
    public sealed class ServiceClient : MicroserviceClient, Beamable.Common.IHaveServiceName
    {
        
        public ServiceClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "Service";
            }
        }
        
        /// <summary>
        /// Call the TriggerNotificationWithDelay method on the Service microservice
        /// <see cref="Beamable.Microservices.Service.TriggerNotificationWithDelay"/>
        /// </summary>
        public Beamable.Common.Promise<string> TriggerNotificationWithDelay(System.Collections.Generic.List<long> playerIds, string messageContext, object payload)
        {
            object raw_playerIds = playerIds;
            object raw_messageContext = messageContext;
            object raw_payload = payload;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("playerIds", raw_playerIds);
            serializedFields.Add("messageContext", raw_messageContext);
            serializedFields.Add("payload", raw_payload);
            return this.Request<string>("Service", "TriggerNotificationWithDelay", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersServiceClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Collections_Generic_List_System_Int64 : MicroserviceClientDataWrapper<System.Collections.Generic.List<long>>
        {
        }
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_String : MicroserviceClientDataWrapper<string>
        {
        }
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Object : MicroserviceClientDataWrapper<object>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForServiceClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<ServiceClient>();
        }
        
        public static ServiceClient Service(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<ServiceClient>();
        }
    }
}
