//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Microservices.Service"/> </summary
    public sealed class ServiceClient : MicroserviceClient, Beamable.Common.IHaveServiceName
    {
        
        public ServiceClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "Service";
            }
        }
        
        /// <summary>
        /// Call the SetLeaderboardScore method on the Service microservice
        /// <see cref="Beamable.Microservices.Service.SetLeaderboardScore"/>
        /// </summary>
        public Beamable.Common.Promise<bool> SetLeaderboardScore(string leaderboardId, int score, System.Collections.Generic.Dictionary<string, object> leaderboardScores)
        {
            object raw_leaderboardId = leaderboardId;
            object raw_score = score;
            object raw_leaderboardScores = leaderboardScores;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("leaderboardId", raw_leaderboardId);
            serializedFields.Add("score", raw_score);
            serializedFields.Add("leaderboardScores", raw_leaderboardScores);
            return this.Request<bool>("Service", "SetLeaderboardScore", serializedFields);
        }
        
        /// <summary>
        /// Call the GetLeaderboard method on the Service microservice
        /// <see cref="Beamable.Microservices.Service.GetLeaderboard"/>
        /// </summary>
        public Beamable.Common.Promise<string> GetLeaderboard()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<string>("Service", "GetLeaderboard", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersServiceClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_String : MicroserviceClientDataWrapper<string>
        {
        }
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Int32 : MicroserviceClientDataWrapper<int>
        {
        }
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Collections_Generic_Dictionary_System_String_System_Object : MicroserviceClientDataWrapper<System.Collections.Generic.Dictionary<string, object>>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForServiceClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<ServiceClient>();
        }
        
        public static ServiceClient Service(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<ServiceClient>();
        }
    }
}
