using System;
using System.Collections;
using System.Collections.Generic;
using System.Threading.Tasks;
using Beamable;
using Beamable.Api.Autogenerated.Leaderboards;
using Beamable.Server.Clients;
using UnityEngine;

public class LeaderboardLoadTest : MonoBehaviour
{ 
    BeamContext _beamContext;
    private ILeaderboardsApi _lbApi;

    private async void Start()
    {
        _beamContext = await BeamContext.Default.Instance;
        _lbApi = _beamContext.ServiceProvider.GetService<ILeaderboardsApi>();
        var leaderboard = await _lbApi.ObjectGetRanks(_beamContext.PlayerId.ToString(), "leaderboards.id");
        Debug.Log($"Current Player Rank: {leaderboard.lb.rankings[0].rank}");
    }
}