using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Beamable.Api.Autogenerated.Models;
using Beamable.Common.Api;
using Beamable.Server;

namespace Beamable.Microservices
{
    [Microservice("Service")]
    public class Service : Microservice
    {
        [ClientCallable]
        public async Task<List<string>> ListAllPlayers()
        {
            // Search for all players with any activity (DAYS_SINCE_INSTALL > -1)
            var request = new StatsSearchRequest
            {
                criteria = new List<SearchCriteria>
                {
                    new SearchCriteriaLong
                    {
                        stat = "DAYS_SINCE_INSTALL",
                        rel = "gt",
                        value = -1
                    }
                }
            };

            var response = await Requester.Request<StatsSearchResponse>(Method.POST, "/basic/stats/search", request);
            return response.ids.ConvertAll(id => id.ToString());
        }

        [ClientCallable]
        public async Task<string> DeleteAccount(string accountId)
        {
            var accountIdResponse = await GetAccountId(accountId);
            var response = await ForgetUser(accountIdResponse);
            return response;
        }
        
        private async Task<string> GetAccountId(string accountId)
        {
            var path = $"/basic/accounts/search?query={accountId}&page=1&pagesize=10";
            var response = await Requester.Request<AccountSearchResponse>(Method.GET, path);
            return response.accounts.First().id.ToString();
        }

        private async Task<string> ForgetUser(string accountId)
        {
            var path = $"/object/accounts/{accountId}/admin/forget";
            var response = await Requester.Request<string>(Method.DELETE, path, parser: (s => s));
            return response;
        }
    }

    [Serializable]
    public class StatsSearchRequest
    {
        public string domain = "game";
        public string access = "private";
        public string objectType = "player";
        public List<SearchCriteria> criteria = new List<SearchCriteria>();
    }

    [Serializable]
    public abstract class SearchCriteria
    {
        public string stat;
        public string rel;
    }

    [Serializable]
    public class SearchCriteriaLong : SearchCriteria
    {
        public long value;
    }

    [Serializable]
    public class StatsSearchResponse
    {
        public List<long> ids;
    }
}
